name: Bug report
description: Report a problem
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: v0.1.0
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide exact steps
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant logs (from %AppData%/DriftOS/logs)
